country = ['China']
print(country)
country.append('Japan')
print(country)
country.insert(0, 'Korea')
print(country)
country.append('Thailand')
country.append('Cuba')
print(country)
country.pop()
print(country)
country.remove('Japan')
print(country)
print(sorted(country))
print(country)
country.sort()
print(country)
country.reverse()
print(country)
print(len(country))